# SPDX-FileCopyrightText: 2026 Blender Authors
#
# SPDX-License-Identifier: GPL-3.0-or-later

"""
Tool-code for returning the world-space bounds, element counts and modifier
settings of objects.
"""

__all__ = (
    "Params",
    "Result",
    "main",
)

from typing import Any, NamedTuple

# Placeholder types for Blender Python objects (no stubs available).
_Depsgraph = Any
_Mesh = Any
_Modifier = Any
_Object = Any


class Params(NamedTuple):
    names: list[str]


class Result(NamedTuple):
    status: str
    objects: list[dict[str, Any]]
    not_found: list[str]


# @include_begin: _template_rna_props_to_json.py
def _rna_value_to_json(value: Any) -> Any:
    return value


def _rna_props_to_json(
        struct: Any,
        skip: tuple[str, ...] = (),
        skip_prefixes: tuple[str, ...] = (),
) -> dict[str, Any]:
    return {}
# @include_end


# Reported at the top level of each modifier (not under `settings`).
_MODIFIER_COMMON = (
    "name",
    "type",
    "show_viewport",
    "show_render",
    "show_in_editmode",
    "show_on_cage",
)
# UI state, not relevant to the result.
_MODIFIER_SKIP = _MODIFIER_COMMON + (
    "is_active",
    "show_expanded",
    "show_group_selector",
    "show_manage_panel",
    "use_pin_to_last",
)
_MODIFIER_SKIP_PREFIXES = ("open_",)


def _mesh_counts(mesh: _Mesh) -> dict[str, int]:
    from array import array

    loop_totals = array("i", bytes(4 * len(mesh.polygons)))
    mesh.polygons.foreach_get("loop_total", loop_totals)
    return {
        "vertices": len(mesh.vertices),
        "edges": len(mesh.edges),
        "faces": len(mesh.polygons),
        # An n-gon is split into n - 2 triangles.
        "triangles": sum(loop_totals) - 2 * len(loop_totals),
    }


# Axis-aligned bounds as `(min, max)`, each a list of 3 floats.
_MinMax = tuple[list[float], list[float]]


def _coords_min_max(coords: Any) -> _MinMax | None:
    """
    Return the bounds of the flat ``x, y, z, ...`` sequence *coords*.
    """
    if not coords:
        return None
    return (
        [min(coords[axis::3]) for axis in range(3)],
        [max(coords[axis::3]) for axis in range(3)],
    )


def _box_min_max(bound_box: Any, matrix: Any) -> _MinMax:
    """
    Return the world-space bounds of the 8 local *bound_box* corners transformed by *matrix*.

    Looser than the geometry itself when *matrix* rotates the box.
    """
    from mathutils import Vector  # pylint: disable=import-error,no-name-in-module

    min_max = _coords_min_max([v for corner in bound_box for v in matrix @ Vector(corner)])
    assert min_max is not None
    return min_max


def _merge_min_max(a: _MinMax | None, b: _MinMax | None) -> _MinMax | None:
    if a is None or b is None:
        return a or b
    return (
        [min(x, y) for x, y in zip(a[0], b[0])],
        [max(x, y) for x, y in zip(a[1], b[1])],
    )


def _instances_by_object(depsgraph: _Depsgraph, objects: list[_Object]) -> dict[int, tuple[int, _MinMax | None]]:
    """
    Return the instance count and bounds of the instances generated by each of *objects*
    (e.g. by Geometry Nodes or collection instancing), keyed by ``session_uid``.
    """
    uids = {obj.session_uid for obj in objects}
    result: dict[int, tuple[int, _MinMax | None]] = {}
    for inst in depsgraph.object_instances:
        if not inst.is_instance or inst.parent is None:
            continue
        uid = inst.parent.original.session_uid
        if uid not in uids:
            continue
        count, min_max = result.get(uid, (0, None))
        result[uid] = (
            count + 1,
            _merge_min_max(min_max, _box_min_max(inst.object.bound_box, inst.matrix_world)),
        )
    return result


def _geometry_info(
        obj: _Object,
        depsgraph: _Depsgraph,
        instances: tuple[int, _MinMax | None],
) -> dict[str, Any]:
    """
    Return world-space bounds and element counts, before and after modifiers.
    """
    from array import array

    counts_original = _mesh_counts(obj.data) if obj.type == 'MESH' else None

    obj_eval = obj.evaluated_get(depsgraph)
    if not obj_eval.is_evaluated:
        # Not in the view layer (e.g. unlinked or in an excluded collection):
        # neither the transform nor the modifiers are evaluated.
        return {
            "is_evaluated": False,
            "bounds_world": None,
            "counts_original": counts_original,
            "counts_evaluated": None,
            "instance_count": None,
        }

    counts_evaluated = None
    min_max = None
    try:
        mesh = obj_eval.to_mesh()
    except RuntimeError:
        # Types that can't be converted to a mesh (e.g. empties, lights).
        mesh = None
    if mesh is not None:
        try:
            counts_evaluated = _mesh_counts(mesh)
            # A temporary copy, transforming it leaves the object untouched.
            mesh.transform(obj_eval.matrix_world)
            coords = array("f", bytes(4 * 3 * len(mesh.vertices)))
            mesh.vertices.foreach_get("co", coords)
            min_max = _coords_min_max(coords)
        finally:
            obj_eval.to_mesh_clear()
    elif obj.type in {'CURVES', 'POINTCLOUD', 'VOLUME', 'GREASEPENCIL'}:
        # No mesh, fall back to the (looser) bounds of the rotated local box.
        min_max = _box_min_max(obj_eval.bound_box, obj_eval.matrix_world)

    # Instances are not part of the mesh, include them in the bounds only.
    instance_count, instances_min_max = instances
    min_max = _merge_min_max(min_max, instances_min_max)

    bounds = None
    if min_max is not None:
        lo, hi = min_max
        bounds = {"min": lo, "max": hi, "size": [b - a for a, b in zip(lo, hi)]}
    return {
        "is_evaluated": True,
        "bounds_world": bounds,
        "counts_original": counts_original,
        "counts_evaluated": counts_evaluated,
        "instance_count": instance_count,
    }


def _nodes_modifier_inputs(mod: _Modifier) -> list[dict[str, Any]]:
    """
    Return the group inputs of a Geometry Nodes modifier, by socket name.
    """
    group = mod.node_group
    if group is None:
        return []
    # Blender 5.2+ exposes the inputs as RNA, older versions as ID properties.
    properties = getattr(mod, "properties", None)
    rna_inputs = properties.inputs if properties is not None else None

    result = []
    for item in group.interface.items_tree:
        if item.item_type != 'SOCKET' or item.in_out != 'INPUT':
            continue
        if item.socket_type == "NodeSocketGeometry":
            continue
        identifier = item.identifier
        info: dict[str, Any] = {
            "name": item.name,
            "identifier": identifier,
            "socket_type": item.socket_type,
        }
        if rna_inputs is not None:
            socket = getattr(rna_inputs, identifier, None)
            if socket is not None:
                info["value"] = _rna_value_to_json(getattr(socket, "value", None))
                info["input_type"] = socket.type
                if hasattr(socket, "attribute_name"):
                    info["attribute_name"] = socket.attribute_name
        elif identifier in mod:
            info["value"] = _rna_value_to_json(mod[identifier])
            if mod.get(identifier + "_use_attribute"):
                info["input_type"] = 'ATTRIBUTE'
                info["attribute_name"] = mod.get(identifier + "_attribute_name", "")
        result.append(info)
    return result


def _modifier_info(mod: _Modifier) -> dict[str, Any]:
    info: dict[str, Any] = {key: getattr(mod, key) for key in _MODIFIER_COMMON}
    info["settings"] = _rna_props_to_json(mod, skip=_MODIFIER_SKIP, skip_prefixes=_MODIFIER_SKIP_PREFIXES)
    if mod.type == 'NODES':
        info["inputs"] = _nodes_modifier_inputs(mod)
    return info


def _object_info(
        obj: _Object,
        depsgraph: _Depsgraph,
        instances: tuple[int, _MinMax | None],
) -> dict[str, Any]:
    info: dict[str, Any] = {
        "name": obj.name,
        "type": obj.type,
    }
    info.update(_geometry_info(obj, depsgraph, instances))
    info["modifiers"] = [_modifier_info(mod) for mod in obj.modifiers]
    return info


def main(params: Params) -> Result:
    import bpy  # pylint: disable=import-error,no-name-in-module

    depsgraph = bpy.context.evaluated_depsgraph_get()
    found = []
    not_found = []
    for name in params.names:
        obj = bpy.data.objects.get(name)
        if obj is None:
            not_found.append(name)
        else:
            found.append(obj)
    instances = _instances_by_object(depsgraph, found)
    return Result(
        status="ok",
        objects=[
            _object_info(obj, depsgraph, instances.get(obj.session_uid, (0, None)))
            for obj in found
        ],
        not_found=not_found,
    )
